### ISSUE TITLE
closing device always error (*pn532.Pn532).Close()

### ISSUE THREAD

**Issue by bokunodev** [asjdf/pn532#1]
```log
panic: Port has been closed

goroutine 17 [running]:
github.com/asjdf/pn532.(*Pn532).initSerialReader.func1()
        /home/guest/.go/pkg/mod/github.com/asjdf/pn532@v0.0.0-20230302150234-6d01a9b80d3a/pn532.go:87 +0xd6
created by github.com/asjdf/pn532.(*Pn532).initSerialReader in goroutine 1
        /home/guest/.go/pkg/mod/github.com/asjdf/pn532@v0.0.0-20230302150234-6d01a9b80d3a/pn532.go:82 +0x56
exit status 2
```

**Comment by bokunodev** [comment]
#2 

sometimes it return `os.ErrClosed` error and since there is not logging mechanism. i think, panic is feasible in this case.
